<a href="https://colab.research.google.com/github/TamaraMaggioni/freecodecamp-intro-to-numpy/blob/master/NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [ ]:
# your code goes here
# opción 1

a = np.array([0,0,0,0,0,0,0,0,0,0])
print(a)


[0 0 0 0 0 0 0 0 0 0]


In [ ]:
np.array([0,0,0,0,0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# opción 2
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#opción 3
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [10]:
# your code goes here

np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [8]:
# your code goes here

# opción 1

M = np.array([
            [1,1],
            [1,1]
])
print(M)
M.dtype

[[1 1]
 [1 1]]


dtype('int64')

In [9]:
#opción 2

M = np.ones([2,2], dtype=np.int)
print(M)

[[1 1]
 [1 1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [16]:
# your code goes here

# opción 1

N = np.array([
            [1.0,1.0],
            [1.0,1.0],
            [1.0,1.0]
])
N.dtype

dtype('float64')

In [17]:
# opción 2

N = np.array([
            [1,1],
            [1,1],
            [1,1]
], dtype=np.float)

In [18]:
# opción 3

np.ones([3,2], dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [24]:
# your code goes here

X = np.arange(4, dtype=np.int)
print(X)
print(X.shape)
X.dtype

[0 1 2 3]
(4,)


dtype('int64')

In [31]:
# opción 1

X[0] = 1
X[2] = 1
X[3] = 1

print(X)

[1 1 1 1]


In [35]:
# opción 2
np.ones(4, dtype=np.int)

array([1, 1, 1, 1])

In [33]:
# opción 3

np.ones_like(X)

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [43]:
# your code goes here

X = np.array([[1,2,3], [4,5,6]], dtype=np.int)
print(X)

[[1 2 3]
 [4 5 6]]


In [41]:
# opción 1

print(X.shape, X.dtype)

(2, 3) int64


In [42]:
np.array([
          [0,0,0],
          [0,0,0]
], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
# opción 2

np.zeros([2,3], dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0]])

In [45]:
# opción 3

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [4]:
# your code goes here

np.ones([4,4], dtype=np.int) *5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [10]:
# your code goes here

X = np.array([[2,3], [6,2]], dtype=np.int)
print(X)
print(X.shape, X.dtype)

[[2 3]
 [6 2]]
(2, 2) int64


In [11]:
np.ones_like(X) *7

array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [13]:
# your code goes here

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [20]:
# your code goes here

np.random.randint(10, size=3)


array([5, 2, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [24]:
# your code goes here

np.random.randn(3,3,3)

array([[[-0.38602509, -0.02503335, -0.83563136],
        [ 0.4150532 , -1.24231033,  1.31075238],
        [-1.05078054,  0.79586824, -1.25566639]],

       [[-0.3370789 , -0.61651195,  1.4013413 ],
        [ 0.71111918,  1.66457913, -0.70925511],
        [ 0.45391143, -0.20657791, -0.54450219]],

       [[ 0.16439326, -0.15832745,  0.26716408],
        [-0.6754279 , -0.7855044 ,  0.37301763],
        [-0.90061782,  1.70157444, -2.20433422]]])

In [27]:
np.random.random((3,3,3)) 

array([[[0.07974206, 0.40366419, 0.34076959],
        [0.58491657, 0.92988907, 0.20018189],
        [0.41698369, 0.86398553, 0.81253868]],

       [[0.33677849, 0.44055646, 0.89190612],
        [0.9549906 , 0.29409272, 0.88436038],
        [0.6716964 , 0.61248237, 0.84733244]],

       [[0.16993993, 0.40030132, 0.05346354],
        [0.59243744, 0.8074005 , 0.00381285],
        [0.79681656, 0.50072249, 0.75082261]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [31]:
# your code goes here
X = [1, 2, 3]
print(X)
print(X, type(X))

[1, 2, 3]
[1, 2, 3] <class 'list'>


In [34]:
Y = np.array(X)
print(Y, type(Y))

[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [ ]:
# your code goes here


In [35]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 139841937722144
[5 2 3] 139842151590688


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [11]:
# your code goes here

np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [13]:
# your code goes here

np.arange(1,11,2)


array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [43]:
# your code goes here

np.arange(10, 0, -1)



array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [44]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [45]:
# your code goes here

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [ ]:
# your code goes here


In [46]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [47]:
# your code goes here
X = np.array(['A','B','C','D','E'])

print(X[0])

A


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [50]:
# your code goes here

print(X[-1])

E


In [54]:
X[len(X)-1]

'E'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [56]:
# your code goes here
X = np.array(['A','B','C','D','E'])

X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [ ]:
# your code goes here


In [57]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [74]:
# your code goes here
print(len(X))
X[::-1]

5


array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [75]:
X[::]

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [85]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-7:-1])

[1 2 3 4 5 6]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [3]:
# your code goes here

X = np.array(['A', 'B', 'C', 'D', 'E'])

X[::2] # Elijo de acá hasta acá elementos, de a 2 pasos

array(['A', 'C', 'E'], dtype='<U1')

In [5]:
X[[0,2,-1]] # Elijo puntualmente estos elementos

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [ ]:
# your code goes here


In [6]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [8]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

array([13, 14, 15, 16])

In [10]:
# your code goes here

X[-1]

array([13, 14, 15, 16])

In [11]:
X.shape

(4, 4)

In [13]:
X[3]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [14]:
# your code goes here

X[0,0]

1

In [15]:
X[0][0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [16]:
# your code goes here

X[-1,-1]

16

In [17]:
X.shape

(4, 4)

In [19]:
X[3,3]

16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

In [20]:
# your code goes here

X.shape

(4, 4)

In [22]:
X[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
X[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [29]:
# your code goes here

X[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [34]:
# your code goes here

X[2:, 2:]

array([[11, 12],
       [15, 16]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [43]:
# your code goes here

X = [-5, -3, 0, 10, 40]

X = np.array(X, dtype=np.float)
print(X)


[-5. -3.  0. 10. 40.]


In [36]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [49]:
# your code goes here

X[::-1]

array([40., 10.,  0., -3., -5.])

In [ ]:
X = [-5, -3, 0, 10, 40]

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [52]:
# your code goes here
np.sort(X)

array([-5., -3.,  0., 10., 40.])

In [53]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [54]:
# your code goes here
X[4] = 1

In [55]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [ ]:
# your code goes here

X[3] = 40

In [56]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [60]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [62]:
# your code goes here
X[3] = 1
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [58]:

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [63]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [65]:
X[3,3] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [ ]:

X[-1, -1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [68]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [69]:
# your code goes here
X +5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [70]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [75]:
# your code goes here

X<0

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [74]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [76]:
X[X<0]

array([-1, -4, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [77]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [78]:
# your code goes here

X[X<0]


array([-1, -4, -9])

In [79]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [80]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [82]:
# your code goes here

X[X > 5]

array([ 6, 10])

In [83]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [84]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [87]:
# your code goes here

mean = X.mean()
print(mean)

0.9


In [88]:
X[X>mean]

array([ 2,  5,  6, 10])

In [89]:


mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [90]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [96]:
# your code goes here

X[(X==2) | (X==10)]


array([ 2, 10])

In [93]:


mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [18]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [19]:
# your code goes here

X!=0


array([ True,  True, False,  True,  True,  True, False, False,  True,
        True])

In [20]:
np.all(X!=0)

False

In [13]:
X = np.array([1,2,3])

In [16]:
X!=0

array([ True,  True,  True])

In [15]:
np.all(X!=0)

True

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [ ]:
# your code goes here


In [115]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

In [8]:
np.any(X==0)

False

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [5]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [6]:
# your code goes here
X.sum()

43

In [21]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

np.sum(X)

43

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [22]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])


In [23]:
# your code goes here

X.mean()

3.7

In [24]:
np.mean(X)

3.7

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [27]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [29]:
# your code goes here
np.sum(X, axis=0)

array([28, 32, 36, 40])

In [30]:
X.sum(axis=0)

array([28, 32, 36, 40])

In [31]:

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [32]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [33]:
# your code goes here
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [34]:
np.mean(X, axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [35]:

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [36]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

In [37]:
# your code goes here
np.max(X)

10

In [38]:

#np.max(X)
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)